apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javareplica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javareplica
  template:
    metadata:
      name: java
      labels:
        app: javareplica
    spec:
      containers:
      - name: java-web-app
        image: dockerhandson/java-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javanewsrc
spec:
  type: NodePort
  selector:
    app: javareplica
  ports:
  - port: 80
    targetPort: 8080
