apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: javads
spec:
  selector:
    matchLabels:
      app: javads
  template:
    metadata:
      labels:
        app: javads
    spec:
      containers:
      - name: javads
        image: dockerhandson/java-web-app:latest
        ports:
        - containerPort: 8080      
---
apiVersion: v1
kind: Service
metadata:
  name: javadsservice
spec:
  type: NodePort
  selector:
    app: javads
  ports:
  - port: 80
    targetPort: 8080
