apiVersion: v1
kind: Pod
metadata:
  name: javasrc
  labels:
    app: javasrc
spec:
  containers:
  - name: javasrc
    image: dockerhandson/java-web-app
    ports: 
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasrc
  labels:
    app: javasrc
spec:
  type: NodePort
  selector:
    app: javasrc
  ports:
  - port: 8080
    targetPort: 8080
