apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mavendaemonset
spec:
  selector:
    matchLabels:
      app: mavends
  template:
    metadata:
      labels:
        app: mavends
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: mavendaemonset
        image: dockerhandson/maven-web-application:2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavendsservice
spec:
  type: NodePort
  selector:
    app: mavends
  ports:
  - port: 80
    targetPort: 8080
