apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata: 
      labels:
        app: mavenapp
    spec:
      containers:      
      - name: maven
        image: dockerhandson/maven-web-application:2
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 20
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080

