apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: mavendeployment
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavendsservice
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
