apiVersion: v1
kind: Service
metadata:
  name: mongosrc
  namespace: springmongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: springmongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: mongosrc
  template:
    metadata:
      labels:
        app: mongo
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongo
            topologyKey: "kubernetes.io/hostname" 
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "mainrepset"
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongovol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
