apiVersion: v1
kind: PersistentVolume
metadata:
  name: springmongopv
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /spring
