apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: springmongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      tolerations:
      - key: node
        operator: Equal
        value: hate01
        effect: NoExecute
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - springapp
            topologyKey: "kubernetes.io/hostname"       
      containers:
      - name: spring
        image: dockerhandson/spring-boot-mongo
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosrc
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: springmongo
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
